apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app         # LEAVE AS IS
  namespace: default # LEAVE AS IS
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator  # <--- CHANGE THIS
      version: 4.3.7 # <--- CHANGE THIS
      sourceRef:
        kind: HelmRepository
        name: minio  # <--- CHANGE THIS
        namespace: flux-system
  values:           # <--- CHANGE THIS
    operator:
      image:
        repository: quay.io/minio/operator

      replicaCount: 1
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000

    console:
      replicaCount: 1
      image:
        repository: quay.io/minio/console
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      ingress:
        enabled: false
