apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app         # LEAVE AS IS
  namespace: default # LEAVE AS IS
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg   # <--- CHANGE THIS
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
