apiVersion: sets.gitops.pro/v1alpha1
kind: GitOpsSet
metadata:
  name: apps-onboarding
  namespace: flux-system
spec:
  generators:
    - gitRepository:
        repositoryRef: flux-system
        directories:
          - path: apps/*/*
  templates:
    # Template 1: Namespace
    # We grab index 2: "."(0) -> "apps"(1) -> "web-servers"(2)
    - content:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: '{{ index (splitList "/" .Element.Directory) 2 }}'
          labels:
            toolkit.fluxcd.io/tenant: '{{ index (splitList "/" .Element.Directory) 2 }}'

    # Template 2: Kustomization
    # We combine Namespace (Index 2) and Release Name (.Element.Base)
    - content:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: '{{ index (splitList "/" .Element.Directory) 2 }}-{{ .Element.Base }}'
          namespace: flux-system
        spec:
          interval: 2m
          sourceRef:
            kind: GitRepository
            name: flux-system
          path: '{{ .Element.Directory }}'
          prune: true
          targetNamespace: '{{ index (splitList "/" .Element.Directory) 2 }}'
