apiVersion: sets.gitops.pro/v1alpha1
kind: GitOpsSet
metadata:
  name: debug-probe
  namespace: flux-system
spec:
  generators:
    - gitRepository:
        repositoryRef: flux-system
        directories:
          - path: apps/web-servers/nginx-chart
  templates:
    - content:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: debug-kustomization-output
          namespace: flux-system
        data:
          # This shows us exactly what Flux is trying to apply
          kustomization.yaml: |
            apiVersion: kustomize.toolkit.fluxcd.io/v1
            kind: Kustomization
            metadata:
              name: test-object
              namespace: flux-system
            spec:
              path: '{{ .Element.Directory }}'
              patches:
                - patch: |
                    - op: replace
                      path: /metadata/name
                      value: {{ .Element.Base }}
                  target:
                    kind: HelmRelease
