apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 15.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1
    service:
      type: ClusterIP
    # Fixing the image pull error by defining specific image settings
    image:
      registry: public.ecr.aws
      repository: bitnami/nginx
      tag: 1.25.3