apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-chart
  namespace: web-servers
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 15.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    image:
      registry: public.ecr.aws
      repository: bitnami/nginx
      tag: latest