apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: "1.28.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    createNamespace: true
  releaseName: cnpg
  targetNamespace: cnpg-system
