apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: base
      version: "1.28.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
  releaseName: istio-base
  targetNamespace: istio-system
